openapi: 3.0.1
info:
  title: ProjectName Gateway
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/staging'

paths:
  /test:
    post:
      tags:
        - Test Tag
      summary: Create a new test
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchemaPayload'
      responses:
        '200':
          description: Test POST successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      tags:
        - Test Tag
      summary: Retrieve a list of tests
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Test GET successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Bad request, e.g., invalid query parameters
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          $ref: '#/components/responses/InternalServerError'

  /test/{id}:
    put:
      tags:
        - Test Tag
      summary: Update an existing test
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchemaPayload'
      responses:
        '200':
          description: Test updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      tags:
        - Test Tag
      summary: Retrieve a test
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '404':
          description: Test not found
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      tags:
        - Test Tag
      summary: Delete a test
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Test deleted successfully
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    SchemaPayload:
      type: object
      properties:
        property1: 
          type: string
        property2: 
          type: number
        propertyRef: 
          $ref: '#/components/schemas/Reference'

    Reference:
      type: object
      properties:
        property1: 
          type: string
        property2: 
          type: string

    Response:
      type: object
      properties:
        property:
          type: string

  responses:
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              message:
                type: string
